esd:
  profiles:
    active: local
  server:
    name: demo
    worker_num: 1
    max_conn: 1024
  port:
    http:
      name: http
      host: 0.0.0.0
      port: 8080
      open_http_protocol: true
      sock_type: 1